services:
  - type: web
    name: medibuddy-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: medibuddy-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
